/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AdministrativeRegion } from "../../administrativeRegion/base/AdministrativeRegion";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { AdministrativeUnit } from "../../administrativeUnit/base/AdministrativeUnit";
import { District } from "../../district/base/District";

@ObjectType()
class Province {
  @ApiProperty({
    required: false,
    type: () => AdministrativeRegion,
  })
  @ValidateNested()
  @Type(() => AdministrativeRegion)
  @IsOptional()
  administrativeRegion?: AdministrativeRegion | null;

  @ApiProperty({
    required: false,
    type: () => AdministrativeUnit,
  })
  @ValidateNested()
  @Type(() => AdministrativeUnit)
  @IsOptional()
  administrativeUnit?: AdministrativeUnit | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  code!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  codeName!: string | null;

  @ApiProperty({
    required: false,
    type: () => [District],
  })
  @ValidateNested()
  @Type(() => District)
  @IsOptional()
  districts?: Array<District>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  fullName!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullNameEn!: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nameEn!: string | null;
}

export { Province as Province };
