http:
  port: 9000

https:
  port: 9876
  hostname: localhost

apiEndpoints:
  api:
    host: "*"
    paths: "/ip"
  publicAccount:
    methods: ["POST", "OPTIONS"]
    host: "*"
    paths:  
      - "/api/users/register"
      - "/api/users/forgot-password"
  account:
    methods: ["GET", "POST", "PATCH", "DELETE", "OPTIONS"]
    host: "*"
    paths: 
      - "/api/users"
      - "/api/users/:id"
      - "/api/users/reset-password"
      - "/api/users/nowLocaion"
      - "/api/users/editUser"
      - "/api/users/pushNoti"
      - "/api/users/userDetail"
      - "/api/users/rankUsesr*"
  auth:
    methods: ["POST"]
    host: "*"
    paths: 
        - "/api/login"
  notification:
    methods: ["GET", "POST", "PATCH", "DELETE", "OPTIONS"]
    host: "*"
    paths: "/api/notifications*"
  publicDonation:
    methods: ["POST", "OPTIONS"]
    host: "*"
    paths: 
        - "/api/donations/addDonaton"
  donation:
    methods: ["GET", "PATCH", "DELETE", "OPTIONS"]
    host: "*"
    paths: 
        - "/api/donations"
        - "/api/donations/:id"
        - "/api/donations/getDonationByUserId"
  mail:
    methods: ["GET", "POST", "PATCH", "DELETE", "OPTIONS"]
    host: "*"
    paths: "/api/mails*"
  publicSupportRequest:
    methods: ["POST", "OPTIONS"]
    host: "*"
    paths: 
        - "/api/supportRequests/addSupportRequests"
        - "/api/supportRequestDetails/getDetail/{id}"
  supportRequest:
    methods: ["GET", "POST", "PATCH", "DELETE", "OPTIONS"]
    host: "*"
    paths: 
        - "/api/supportRequests"
        - "/api/supportRequests/handleSupportRequest"
        - "/api/supportRequests/:id"
        - "/api/supportRequestTypes*"
        - "/api/supportRequests/getSupportRequestByUserId"
  warehouse:
    methods: ["GET", "POST", "PATCH", "DELETE", "OPTIONS"]
    host: "*"
    paths: "/api/warehouses*"
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  accountService:
    url: "http://user:8000"
  authService:
    url: "http://user:8000"
  notificationService:
    url: "http://notification:8001"
  donationService:
    url: "http://donation:8005"
  mailService:
    url: "http://mail:8004"
  supportRequestService:
    url: "http://support-request:8006"
  warehouseService:
    url: "http://warehouse:8002"
policies:
  - cors
  - log
  - proxy
  - request-transformer
  # - jwt
  - jwt-decoder-policy
  - log-policy
  - rate-limit

  # - express-gateway-plugin-example

pipelines:
  bin:
    apiEndpoints:
      - api
    policies:
      - jwt-decoder-policy:
          action:
              secret: 'asasasa'
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  account:
    apiEndpoints:
      - account
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "*"
              preflightContinue: false
              optionsSuccessStatus: 204
      - jwt-decoder-policy:
            action:
                secret: 'asasasa'
      - log:
          - action:
              message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          - action:
              headers:
                add:
                  requestID: "requestID"
                  user: req.user
      - proxy:
          - action:
              serviceEndpoint: accountService
  publicAccount:
    apiEndpoints:
      - publicAccount
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "*"
              preflightContinue: false
              optionsSuccessStatus: 204
      # - jwt-decoder-policy:
      #       action:
      #           secret: 'asasasa'
      - log:
          - action:
              message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          - action:
              headers:
                add:
                  requestID: "requestID"
                  # user: req.user
      - proxy:
          - action:
              serviceEndpoint: accountService
  auth:
    apiEndpoints:
      - auth
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "*"
              preflightContinue: false
              optionsSuccessStatus: 204
      - log:
          - action:
              message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          - action:
              headers:
                add:
                  requestID: "requestID"
                  # user: req.user
      - proxy:
          - action:
              serviceEndpoint: authService
  notification:
    apiEndpoints:
      - notification
    policies:
      # - jwt-decoder-policy:
      #     action:
      #         secret: 'asasasa'
      - log:
          - action:
              message: "${req.method} ${req.originalUrl}"
      - log-policy:
          - action:
              logLevel: "debug"
      - request-transformer:
          - action:
              headers:
                add:
                  requestID: "requestID"
                  # user: req.user
      - proxy:
          - action:
              serviceEndpoint: notificationService
  mail:
    apiEndpoints:
      - mail
    policies:
      # - jwt-decoder-policy:
      #     action:
      #         secret: 'asasasa'
      - log:
          - action:
              message: "${req.method} ${req.originalUrl}"
      - log-policy:
          - action:
              logLevel: "debug"
      - request-transformer:
          - action:
              headers:
                add:
                  requestID: "requestID"
                  # user: req.user
      - proxy:
          - action:
              serviceEndpoint: mailService
  donation:
    apiEndpoints:
      - donation
    policies:
      - jwt-decoder-policy:
            action:
                secret: 'asasasa'
      - log:
          - action:
              message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          - action:
              headers:
                add:
                  requestID: "requestID"
                  user: req.user
      - proxy:
          - action:
              serviceEndpoint: donationService
  publicDonation:
    apiEndpoints:
      - publicDonation
    policies:
      - log:
          - action:
              message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          - action:
              headers:
                add:
                  requestID: "requestID"
      - proxy:
          - action:
              serviceEndpoint: donationService
  supportRequest:
    apiEndpoints:
      - supportRequest
    policies:
      - jwt-decoder-policy:
            action:
                secret: 'asasasa'
      - log:
          - action:
              message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          - action:
              headers:
                add:
                  requestID: "requestID"
                  user: req.user
      - proxy:
          - action:
              serviceEndpoint: supportRequestService
  publicSupportRequest:
    apiEndpoints:
      - publicSupportRequest
    policies:
      - log:
          - action:
              message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          - action:
              headers:
                add:
                  requestID: "requestID"
                  user: req.user
      - proxy:
          - action:
              serviceEndpoint: supportRequestService
  warehouse:
    apiEndpoints:
      - warehouse
    policies:
      - jwt-decoder-policy:
            action:
                secret: 'asasasa'
      - log:
          - action:
              message: "${req.method} ${req.originalUrl}"
      - request-transformer:
          - action:
              headers:
                add:
                  requestID: "requestID"
                  user: req.user
      - proxy:
          - action:
              serviceEndpoint: warehouseService

