# Core
db:
  redis:
    emulate: true
    namespace: EG

plugins:
  express-gateway-plugin-jwt-decoder:
    enabled: true
    secret: "asasasa"
    algorithm: "HS256"
  express-gateway-plugin-logging:
    enabled: true
    # level: "info"
    # format: "json" 

policies:
  - jwt-decoder-policy
  - log-policy
crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000

