# Core
db:
  redis:
    emulate: true
    namespace: EG

plugins:
  express-gateway-plugin-jwt-decoder:
    enabled: true
    secret: "asasasa"
    algorithm: "HS256"
    header: "x-jwt-data" 

policies:
  - jwt-decoder-policy
crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10
  
# Cấu hình logger
log:
  level: debug         # Mức độ log: debug, info, warn, error, ...
  transports:
    - file:
        level: debug
        filename: ./logs/express-gateway.log  # Đường dẫn file log
        maxsize: 10485760   # Kích thước tối đa của file log (10MB)
        maxFiles: 5         # Số file log tối đa trước khi bắt đầu ghi đè
    - console:
        level: info    

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000

# plugins:
#   jwt-payload-extractor:
#     secretOrPublicKey: "./certs/token.public.pem" 
