/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HistorySupportService } from "../historySupport.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HistorySupportCreateInput } from "./HistorySupportCreateInput";
import { HistorySupport } from "./HistorySupport";
import { HistorySupportFindManyArgs } from "./HistorySupportFindManyArgs";
import { HistorySupportWhereUniqueInput } from "./HistorySupportWhereUniqueInput";
import { HistorySupportUpdateInput } from "./HistorySupportUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HistorySupportControllerBase {
  constructor(
    protected readonly service: HistorySupportService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HistorySupport })
  @nestAccessControl.UseRoles({
    resource: "HistorySupport",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createHistorySupport(
    @common.Body() data: HistorySupportCreateInput
  ): Promise<HistorySupport> {
    return await this.service.createHistorySupport({
      data: data,
      select: {
        city: true,
        createdAt: true,
        description: true,
        district: true,
        fullname: true,
        id: true,
        phone: true,
        requestSupportId: true,
        updatedAt: true,
        userId: true,
        ward: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [HistorySupport] })
  @ApiNestedQuery(HistorySupportFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "HistorySupport",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async historySupports(
    @common.Req() request: Request
  ): Promise<HistorySupport[]> {
    const args = plainToClass(HistorySupportFindManyArgs, request.query);
    return this.service.historySupports({
      ...args,
      select: {
        city: true,
        createdAt: true,
        description: true,
        district: true,
        fullname: true,
        id: true,
        phone: true,
        requestSupportId: true,
        updatedAt: true,
        userId: true,
        ward: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HistorySupport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HistorySupport",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async historySupport(
    @common.Param() params: HistorySupportWhereUniqueInput
  ): Promise<HistorySupport | null> {
    const result = await this.service.historySupport({
      where: params,
      select: {
        city: true,
        createdAt: true,
        description: true,
        district: true,
        fullname: true,
        id: true,
        phone: true,
        requestSupportId: true,
        updatedAt: true,
        userId: true,
        ward: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HistorySupport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HistorySupport",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateHistorySupport(
    @common.Param() params: HistorySupportWhereUniqueInput,
    @common.Body() data: HistorySupportUpdateInput
  ): Promise<HistorySupport | null> {
    try {
      return await this.service.updateHistorySupport({
        where: params,
        data: data,
        select: {
          city: true,
          createdAt: true,
          description: true,
          district: true,
          fullname: true,
          id: true,
          phone: true,
          requestSupportId: true,
          updatedAt: true,
          userId: true,
          ward: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HistorySupport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HistorySupport",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteHistorySupport(
    @common.Param() params: HistorySupportWhereUniqueInput
  ): Promise<HistorySupport | null> {
    try {
      return await this.service.deleteHistorySupport({
        where: params,
        select: {
          city: true,
          createdAt: true,
          description: true,
          district: true,
          fullname: true,
          id: true,
          phone: true,
          requestSupportId: true,
          updatedAt: true,
          userId: true,
          ward: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
