/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AdministrativeUnitWhereUniqueInput } from "../../administrativeUnit/base/AdministrativeUnitWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { ProvinceWhereUniqueInput } from "../../province/base/ProvinceWhereUniqueInput";
import { WardUpdateManyWithoutDistrictsInput } from "./WardUpdateManyWithoutDistrictsInput";

@InputType()
class DistrictUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AdministrativeUnitWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AdministrativeUnitWhereUniqueInput)
  @IsOptional()
  @Field(() => AdministrativeUnitWhereUniqueInput, {
    nullable: true,
  })
  administrativeUnit?: AdministrativeUnitWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  code?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  codeName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullNameEn?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nameEn?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProvinceWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProvinceWhereUniqueInput)
  @IsOptional()
  @Field(() => ProvinceWhereUniqueInput, {
    nullable: true,
  })
  province?: ProvinceWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => WardUpdateManyWithoutDistrictsInput,
  })
  @ValidateNested()
  @Type(() => WardUpdateManyWithoutDistrictsInput)
  @IsOptional()
  @Field(() => WardUpdateManyWithoutDistrictsInput, {
    nullable: true,
  })
  wards?: WardUpdateManyWithoutDistrictsInput;
}

export { DistrictUpdateInput as DistrictUpdateInput };
