/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AdministrativeUnit } from "../../administrativeUnit/base/AdministrativeUnit";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { Province } from "../../province/base/Province";
import { Ward } from "../../ward/base/Ward";

@ObjectType()
class District {
  @ApiProperty({
    required: false,
    type: () => AdministrativeUnit,
  })
  @ValidateNested()
  @Type(() => AdministrativeUnit)
  @IsOptional()
  administrativeUnit?: AdministrativeUnit | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  code!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  codeName!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullName!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullNameEn!: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nameEn!: string | null;

  @ApiProperty({
    required: false,
    type: () => Province,
  })
  @ValidateNested()
  @Type(() => Province)
  @IsOptional()
  province?: Province | null;

  @ApiProperty({
    required: false,
    type: () => [Ward],
  })
  @ValidateNested()
  @Type(() => Ward)
  @IsOptional()
  wards?: Array<Ward>;
}

export { District as District };
