/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsInt,
  Min,
  Max,
  IsEnum,
  ValidateNested,
} from "class-validator";
import { EnumSupportRequestStatus } from "./EnumSupportRequestStatus";
import { SupportRequestDetailCreateNestedManyWithoutSupportRequestsInput } from "./SupportRequestDetailCreateNestedManyWithoutSupportRequestsInput";
import { Type } from "class-transformer";
import { SupportRequestTypeWhereUniqueInput } from "../../supportRequestType/base/SupportRequestTypeWhereUniqueInput";

@InputType()
class SupportRequestCreateInput {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  city!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  detailAdrdess?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  district!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  email!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  fullname!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  phone!: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  quantity?: number | null;

  @ApiProperty({
    required: true,
    enum: EnumSupportRequestStatus,
  })
  @IsEnum(EnumSupportRequestStatus)
  @Field(() => EnumSupportRequestStatus)
  status!: "Pending" | "Processed";

  @ApiProperty({
    required: false,
    type: () => SupportRequestDetailCreateNestedManyWithoutSupportRequestsInput,
  })
  @ValidateNested()
  @Type(() => SupportRequestDetailCreateNestedManyWithoutSupportRequestsInput)
  @IsOptional()
  @Field(
    () => SupportRequestDetailCreateNestedManyWithoutSupportRequestsInput,
    {
      nullable: true,
    }
  )
  supportRequestDetails?: SupportRequestDetailCreateNestedManyWithoutSupportRequestsInput;

  @ApiProperty({
    required: true,
    type: () => SupportRequestTypeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SupportRequestTypeWhereUniqueInput)
  @Field(() => SupportRequestTypeWhereUniqueInput)
  supportRequestTypeId!: SupportRequestTypeWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  ward!: string;
}

export { SupportRequestCreateInput as SupportRequestCreateInput };
