/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SupportRequestTypeService } from "../supportRequestType.service";
import { SupportRequestTypeCreateInput } from "./SupportRequestTypeCreateInput";
import { SupportRequestType } from "./SupportRequestType";
import { SupportRequestTypeFindManyArgs } from "./SupportRequestTypeFindManyArgs";
import { SupportRequestTypeWhereUniqueInput } from "./SupportRequestTypeWhereUniqueInput";
import { SupportRequestTypeUpdateInput } from "./SupportRequestTypeUpdateInput";
import { SupportRequestFindManyArgs } from "../../supportRequest/base/SupportRequestFindManyArgs";
import { SupportRequest } from "../../supportRequest/base/SupportRequest";
import { SupportRequestWhereUniqueInput } from "../../supportRequest/base/SupportRequestWhereUniqueInput";

export class SupportRequestTypeControllerBase {
  constructor(protected readonly service: SupportRequestTypeService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SupportRequestType })
  async createSupportRequestType(
    @common.Body() data: SupportRequestTypeCreateInput
  ): Promise<SupportRequestType> {
    return await this.service.createSupportRequestType({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [SupportRequestType] })
  @ApiNestedQuery(SupportRequestTypeFindManyArgs)
  async supportRequestTypes(
    @common.Req() request: Request
  ): Promise<SupportRequestType[]> {
    const args = plainToClass(SupportRequestTypeFindManyArgs, request.query);
    return this.service.supportRequestTypes({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SupportRequestType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async supportRequestType(
    @common.Param() params: SupportRequestTypeWhereUniqueInput
  ): Promise<SupportRequestType | null> {
    const result = await this.service.supportRequestType({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SupportRequestType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSupportRequestType(
    @common.Param() params: SupportRequestTypeWhereUniqueInput,
    @common.Body() data: SupportRequestTypeUpdateInput
  ): Promise<SupportRequestType | null> {
    try {
      return await this.service.updateSupportRequestType({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SupportRequestType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSupportRequestType(
    @common.Param() params: SupportRequestTypeWhereUniqueInput
  ): Promise<SupportRequestType | null> {
    try {
      return await this.service.deleteSupportRequestType({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/supportRequests")
  @ApiNestedQuery(SupportRequestFindManyArgs)
  async findSupportRequests(
    @common.Req() request: Request,
    @common.Param() params: SupportRequestTypeWhereUniqueInput
  ): Promise<SupportRequest[]> {
    const query = plainToClass(SupportRequestFindManyArgs, request.query);
    const results = await this.service.findSupportRequests(params.id, {
      ...query,
      select: {
        city: true,
        createdAt: true,
        description: true,
        detailAdrdess: true,
        district: true,
        email: true,
        fullname: true,
        id: true,
        phone: true,
        quantity: true,
        status: true,

        supportRequestTypeID: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        ward: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/supportRequests")
  async connectSupportRequests(
    @common.Param() params: SupportRequestTypeWhereUniqueInput,
    @common.Body() body: SupportRequestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      supportRequests: {
        connect: body,
      },
    };
    await this.service.updateSupportRequestType({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/supportRequests")
  async updateSupportRequests(
    @common.Param() params: SupportRequestTypeWhereUniqueInput,
    @common.Body() body: SupportRequestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      supportRequests: {
        set: body,
      },
    };
    await this.service.updateSupportRequestType({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/supportRequests")
  async disconnectSupportRequests(
    @common.Param() params: SupportRequestTypeWhereUniqueInput,
    @common.Body() body: SupportRequestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      supportRequests: {
        disconnect: body,
      },
    };
    await this.service.updateSupportRequestType({
      where: params,
      data,
      select: { id: true },
    });
  }
}
