/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { DistrictCreateNestedManyWithoutAdministrativeUnitsInput } from "./DistrictCreateNestedManyWithoutAdministrativeUnitsInput";
import { Type } from "class-transformer";
import { ProvinceCreateNestedManyWithoutAdministrativeUnitsInput } from "./ProvinceCreateNestedManyWithoutAdministrativeUnitsInput";
import { WardCreateNestedManyWithoutAdministrativeUnitsInput } from "./WardCreateNestedManyWithoutAdministrativeUnitsInput";

@InputType()
class AdministrativeUnitCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  codeName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  codeNameEn?: string | null;

  @ApiProperty({
    required: false,
    type: () => DistrictCreateNestedManyWithoutAdministrativeUnitsInput,
  })
  @ValidateNested()
  @Type(() => DistrictCreateNestedManyWithoutAdministrativeUnitsInput)
  @IsOptional()
  @Field(() => DistrictCreateNestedManyWithoutAdministrativeUnitsInput, {
    nullable: true,
  })
  districts?: DistrictCreateNestedManyWithoutAdministrativeUnitsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullNameEn?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProvinceCreateNestedManyWithoutAdministrativeUnitsInput,
  })
  @ValidateNested()
  @Type(() => ProvinceCreateNestedManyWithoutAdministrativeUnitsInput)
  @IsOptional()
  @Field(() => ProvinceCreateNestedManyWithoutAdministrativeUnitsInput, {
    nullable: true,
  })
  provinces?: ProvinceCreateNestedManyWithoutAdministrativeUnitsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  shortName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  shortNameEn?: string | null;

  @ApiProperty({
    required: false,
    type: () => WardCreateNestedManyWithoutAdministrativeUnitsInput,
  })
  @ValidateNested()
  @Type(() => WardCreateNestedManyWithoutAdministrativeUnitsInput)
  @IsOptional()
  @Field(() => WardCreateNestedManyWithoutAdministrativeUnitsInput, {
    nullable: true,
  })
  wards?: WardCreateNestedManyWithoutAdministrativeUnitsInput;
}

export { AdministrativeUnitCreateInput as AdministrativeUnitCreateInput };
