/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { DistrictListRelationFilter } from "../../district/base/DistrictListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { ProvinceListRelationFilter } from "../../province/base/ProvinceListRelationFilter";
import { WardListRelationFilter } from "../../ward/base/WardListRelationFilter";

@InputType()
class AdministrativeUnitWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  codeName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  codeNameEn?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => DistrictListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DistrictListRelationFilter)
  @IsOptional()
  @Field(() => DistrictListRelationFilter, {
    nullable: true,
  })
  districts?: DistrictListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  fullName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  fullNameEn?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => ProvinceListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ProvinceListRelationFilter)
  @IsOptional()
  @Field(() => ProvinceListRelationFilter, {
    nullable: true,
  })
  provinces?: ProvinceListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  shortName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  shortNameEn?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => WardListRelationFilter,
  })
  @ValidateNested()
  @Type(() => WardListRelationFilter)
  @IsOptional()
  @Field(() => WardListRelationFilter, {
    nullable: true,
  })
  wards?: WardListRelationFilter;
}

export { AdministrativeUnitWhereInput as AdministrativeUnitWhereInput };
