/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { DistrictUpdateManyWithoutAdministrativeUnitsInput } from "./DistrictUpdateManyWithoutAdministrativeUnitsInput";
import { Type } from "class-transformer";
import { ProvinceUpdateManyWithoutAdministrativeUnitsInput } from "./ProvinceUpdateManyWithoutAdministrativeUnitsInput";
import { WardUpdateManyWithoutAdministrativeUnitsInput } from "./WardUpdateManyWithoutAdministrativeUnitsInput";

@InputType()
class AdministrativeUnitUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  codeName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  codeNameEn?: string | null;

  @ApiProperty({
    required: false,
    type: () => DistrictUpdateManyWithoutAdministrativeUnitsInput,
  })
  @ValidateNested()
  @Type(() => DistrictUpdateManyWithoutAdministrativeUnitsInput)
  @IsOptional()
  @Field(() => DistrictUpdateManyWithoutAdministrativeUnitsInput, {
    nullable: true,
  })
  districts?: DistrictUpdateManyWithoutAdministrativeUnitsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullNameEn?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProvinceUpdateManyWithoutAdministrativeUnitsInput,
  })
  @ValidateNested()
  @Type(() => ProvinceUpdateManyWithoutAdministrativeUnitsInput)
  @IsOptional()
  @Field(() => ProvinceUpdateManyWithoutAdministrativeUnitsInput, {
    nullable: true,
  })
  provinces?: ProvinceUpdateManyWithoutAdministrativeUnitsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  shortName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  shortNameEn?: string | null;

  @ApiProperty({
    required: false,
    type: () => WardUpdateManyWithoutAdministrativeUnitsInput,
  })
  @ValidateNested()
  @Type(() => WardUpdateManyWithoutAdministrativeUnitsInput)
  @IsOptional()
  @Field(() => WardUpdateManyWithoutAdministrativeUnitsInput, {
    nullable: true,
  })
  wards?: WardUpdateManyWithoutAdministrativeUnitsInput;
}

export { AdministrativeUnitUpdateInput as AdministrativeUnitUpdateInput };
